services:
  load_balancer:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - "./load-balancer/nginx.conf:/etc/nginx/nginx.conf"
    networks:
      - rede-compose
    depends_on:
      - site1
      - site2
      - site3

  site1:
    image: matheuslessa/nginx:cor1
    networks:
      - rede-compose

  site2:
    image: matheuslessa/nginx:cor2
    networks:
      - rede-compose

  site3:
    image: matheuslessa/nginx:cor3
    networks:
      - rede-compose

networks:
  rede-compose:
    driver: bridge
