services:
  load_balancer:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - "./load-balancer/nginx.conf:/etc/nginx/nginx.conf"
    networks:
      - rede-compose
    depends_on:
      - site1
      - site2
      - site3

  site1:
<<<<<<< HEAD:docker/docker-compose.yaml
    # Muda a descrição imagem para o nome do container que você criou
=======
    # Muda o nome da imagem para o container que você fez a criação
>>>>>>> 4dfe1f45fa40bb4429f18446a291709d85e73c5d:docker-compose.yaml
    image: matheuslessa/nginx:cor1
    networks:
      - rede-compose

  site2:
<<<<<<< HEAD:docker/docker-compose.yaml
    # Muda a descrição imagem para o nome do container que você criou
=======
    # Muda o nome da imagem para o container que você fez a criação
>>>>>>> 4dfe1f45fa40bb4429f18446a291709d85e73c5d:docker-compose.yaml
    image: matheuslessa/nginx:cor2
    networks:
      - rede-compose

  site3:
<<<<<<< HEAD:docker/docker-compose.yaml
    # Muda a descrição imagem para o nome do container que você criou
=======
    # Muda o nome da imagem para o container que você fez a criação
>>>>>>> 4dfe1f45fa40bb4429f18446a291709d85e73c5d:docker-compose.yaml
    image: matheuslessa/nginx:cor3
    networks:
      - rede-compose

networks:
  rede-compose:
    driver: bridge
